import type { Metadata } from 'next'

import { cn } from '@/lib/utils'
import { fontHeading, fontSans } from '@/styles/fonts'

import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className='scroll-smooth' suppressHydrationWarning>
      <body
        className={cn('min-h-screen antialiased',
          fontSans.variable, fontHeading.variable
        )}>
        {children}
      </body>
    </html>
  )
}
